server:
  port: 8088
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/logistic_web_app_service_login?createDatabaseIfNotExist=true&useSSL=false&serverTimezone=UTC
    #url: ${SPRING_DATASOURCE_URL:jdbc:mysql://ubuntu-server-01.local:3399/ShopApp?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true}
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    
    password: 123456
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: none
  messages:
    basename: i18n/messages
    encoding: UTF-8
    default-locale: en
  redis:
    data:
      host: localhost
      port: 6379
api:
  prefix: /api/v1
jwt:
  expiration: 2592000
  secretKey: a5RsQm2rhY3GMgD51qK3E+aYPoe5IsnfYD0QFydCoQ0=
  expiration-refresh-token: 5184000 #60 days = 60 * 24 * 60 * 60
# swagger-ui custom path
springdoc:
  swagger-ui:
    path: /swagger-ui.html
  api-docs:
    path: /api-docs
  show-actuator: true 
 